import { Injectable, signal, computed } from '@angular/core';

export type LangCode = 'en' | 'he' | 'it' | 'es' | 'pt' | 'yue' | 'ja' | 'ko' | 'th';

@Injectable({ providedIn: 'root' })
export class LanguageService {
  currentLang = signal<LangCode>('en');
  dir = computed(() => (this.currentLang() === 'he' ? 'rtl' : 'ltr'));

  translations: Record<LangCode, any> = {
    en: {
      appName: "Nof Angular",
      baseColor: "Base Color",
      mode: "Mode",
      output: "Output",
      analogous: "Analogous",
      triad: "Triad",
      complementary: "Complementary",
      splitComp: "Split Complementary",
      square: "Square",
      tetradic: "Tetradic",
      monochromatic: "Monochromatic",
      firstColor: "First Color",
      secondColor: "Second Color",
      creditInfoTitle: "Credit & Info",
      creditDescription: "The existence of this project wouldn't've been possible without the following:",
      poweredBy: "Powered by",
      namerUi: "Namer UI",
      contrastRatio: "Contrast Ratio:",
      language: "Language",
      madeBy: "Made by",
      maximBortnikov: "Maxim Bortnikov",
    },
    he: {
      appName: "נוף אנגולר",
      baseColor: "צבע בסיס",
      mode: "מצב",
      output: "פלט",
      analogous: "אנלוגי",
      triad: "טריאדה",
      complementary: "משלים",
      splitComp: "משלים מפוצל",
      square: "ריבועי",
      tetradic: "טטראדי",
      monochromatic: "מונוכרומטי",
      firstColor: "צבע ראשון",
      secondColor: "צבע שני",
      creditInfoTitle: "קרדיט ומידע",
      creditDescription: "הפרויקט הזה לא היה אפשרי בלעדי התרומות הבאות:",
      poweredBy: "מופעל על ידי",
      namerUi: "UI נמר",
      contrastRatio: "יחס ניגודיות:",
      language: "שפה",
      madeBy: "נוצר על ידי",
      maximBortnikov: "מקסים בורטניקוב",
    },
    it: {
      appName: "Nof Angular",
      baseColor: "Colore base",
      mode: "Modalità",
      output: "Output",
      analogous: "Analoghi",
      triad: "Triade",
      complementary: "Complementare",
      splitComp: "Complementare diviso",
      square: "Quadrato",
      tetradic: "Tetradico",
      monochromatic: "Monocromatico",
      firstColor: "Primo colore",
      secondColor: "Secondo colore",
      creditInfoTitle: "Credito e Info",
      creditDescription: "L'esistenza di questo progetto non sarebbe stata possibile senza i seguenti:",
      poweredBy: "Realizzato con",
      namerUi: "Namer UI",
      contrastRatio: "Rapporto di contrasto:",
      language: "Lingua",
      madeBy: "Realizzato da",
      maximBortnikov: "Maxim Bortnikov",
    },
    es: {
      appName: "Nof Angular",
      baseColor: "Color base",
      mode: "Modo",
      output: "Salida",
      analogous: "Análogas",
      triad: "Tríada",
      complementary: "Complementario",
      splitComp: "Complementario dividido",
      square: "Cuadrado",
      tetradic: "Tetrádico",
      monochromatic: "Monocromático",
      firstColor: "Primer color",
      secondColor: "Segundo color",
      creditInfoTitle: "Crédito e Información",
      creditDescription: "La existencia de este proyecto no habría sido posible sin los siguientes:",
      poweredBy: "Desarrollado por",
      namerUi: "Namer UI",
      contrastRatio: "Relación de contraste:",
      language: "Idioma",
      madeBy: "Hecho por",
      maximBortnikov: "Maxim Bortnikov",
    },
    pt: {
      appName: "Nof Angular",
      baseColor: "Cor base",
      mode: "Modo",
      output: "Saída",
      analogous: "Análogas",
      triad: "Tríade",
      complementary: "Complementar",
      splitComp: "Complementar dividido",
      square: "Quadrado",
      tetradic: "Tetrádico",
      monochromatic: "Monocromático",
      firstColor: "Primeira cor",
      secondColor: "Segunda cor",
      creditInfoTitle: "Crédito e Informação",
      creditDescription: "A existência deste projeto não teria sido possível sem os seguintes:",
      poweredBy: "Desenvolvido por",
      namerUi: "Namer UI",
      contrastRatio: "Relação de contraste:",
      language: "Idioma",
      madeBy: "Feito por",
      maximBortnikov: "Maxim Bortnikov",
    },
    yue: {
      appName: "Nof Angular",
      baseColor: "基礎色",
      mode: "模式",
      output: "輸出",
      analogous: "類似色",
      triad: "三色配色",
      complementary: "互補色",
      splitComp: "分補色",
      square: "四方色",
      tetradic: "四色配色",
      monochromatic: "單色調",
      firstColor: "第一色",
      secondColor: "第二色",
      creditInfoTitle: "功勞與資訊",
      creditDescription: "呢個項目唔可以冇以下貢獻：",
      poweredBy: "用緊",
      namerUi: "Namer UI",
      contrastRatio: "對比度：",
      language: "語言",
      madeBy: "整咗由",
      maximBortnikov: "Maxim Bortnikov",
    },
    ja: {
      appName: "Nof Angular",
      baseColor: "ベースカラー",
      mode: "モード",
      output: "出力",
      analogous: "類似色",
      triad: "トライアド",
      complementary: "補色",
      splitComp: "分割補色",
      square: "四角形",
      tetradic: "テトラディック",
      monochromatic: "単色",
      firstColor: "最初の色",
      secondColor: "二番目の色",
      creditInfoTitle: "クレジットと情報",
      creditDescription: "このプロジェクトは以下の貢献なしには実現できませんでした：",
      poweredBy: "Powered by",
      namerUi: "Namer UI",
      contrastRatio: "コントラスト比：",
      language: "言語",
      madeBy: "作成者：",
      maximBortnikov: "Maxim Bortnikov",
    },
    ko: {
      appName: "Nof Angular",
      baseColor: "기본 색상",
      mode: "모드",
      output: "출력",
      analogous: "유사 색상",
      triad: "삼각 배색",
      complementary: "보색",
      splitComp: "분할 보색",
      square: "사각 배색",
      tetradic: "사각 배색",
      monochromatic: "단색",
      firstColor: "첫 번째 색상",
      secondColor: "두 번째 색상",
      creditInfoTitle: "크레딧 및 정보",
      creditDescription: "이 프로젝트는 다음 기여 없이는 불가능했을 것입니다:",
      poweredBy: "Powered by",
      namerUi: "Namer UI",
      contrastRatio: "명암 대비:",
      language: "언어",
      madeBy: "만든 사람:",
      maximBortnikov: "Maxim Bortnikov",
    },
    th: {
      appName: "Nof Angular",
      baseColor: "สีฐาน",
      mode: "โหมด",
      output: "ผลลัพธ์",
      analogous: "สีใกล้เคียง",
      triad: "ไตรภาค",
      complementary: "สีเสริม",
      splitComp: "สีเสริมแยก",
      square: "สี่เหลี่ยม",
      tetradic: "สี่สี",
      monochromatic: "เดี่ยวสี",
      firstColor: "สีแรก",
      secondColor: "สีที่สอง",
      creditInfoTitle: "เครดิตและข้อมูล",
      creditDescription: "โครงการนี้จะไม่เป็นไปได้หากไม่มีส่วนร่วมต่อไปนี้:",
      poweredBy: "ขับเคลื่อนโดย",
      namerUi: "Namer UI",
      contrastRatio: "อัตราส่วนคอนทราสต์:",
      language: "ภาษา",
      madeBy: "สร้างโดย",
      maximBortnikov: "Maxim Bortnikov",
    }
  };


  t(key: string): string {
    return this.translations[this.currentLang()][key] || key;
  }

  setLang(code: LangCode) {
    this.currentLang.set(code);
  }
}